# open | close
mode: close
whiteList:
  - fonts.gstatic.com
  - fonts.googleapis.com
  - kit.fontawesome.com
  - ka-f.fontawesome.com
  - cdn.jsdelivr.net
cache:
  enabled: true
  ttl: P1D
debug: true
