# open | close
mode: close
whitelist:
  - fonts.gstatic.com
  - fonts.googleapis.com
  - kit.fontawesome.com
  - ka-f.fontawesome.com
  - cdn.jsdelivr.com
cache:
  enabled: false
  ttl: P1D
debug: true